// Custom worker entrypoint that wraps the OpenNext-generated handler and
// attaches a `scheduled()` handler for the daily quiz selection cron.
//
// Build flow:
//   1. `opennextjs-cloudflare build` generates `.open-next/worker.js`
//   2. wrangler bundles THIS file as `main` and resolves the import below
//   3. `wrangler deploy` (or `wrangler dev`) ships both fetch and scheduled
//
// The cron schedule lives in wrangler.jsonc → triggers.crons.

import { drizzle } from "drizzle-orm/d1";
// biome-ignore lint/correctness/noUnusedImports: generated at build time
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Path generated by opennextjs-cloudflare build; absent in a fresh checkout.
import openNextHandler from "./.open-next/worker.js";
import { selectDailyQuiz } from "./lib/quiz/select";

function nextUtcDate(now: Date = new Date()): string {
  const d = new Date(now);
  d.setUTCDate(d.getUTCDate() + 1);
  return d.toISOString().slice(0, 10);
}

const handler: ExportedHandler<CloudflareEnv> = {
  fetch: (
    openNextHandler as ExportedHandler<CloudflareEnv>
  ).fetch as ExportedHandlerFetchHandler<CloudflareEnv>,

  async scheduled(event, env, ctx) {
    const date = nextUtcDate();
    const db = drizzle(env.DB);
    try {
      const result = await selectDailyQuiz(db, date);
      console.log(
        `[cron] daily quiz for ${date}: ${result.reused ? "reused" : "selected"} (id=${result.id})`,
      );
    } catch (err) {
      console.error(`[cron] failed to select quiz for ${date}:`, err);
      throw err;
    }
  },
};

export default handler;
